function frame_ids = instantaneous_frame_ids(settings, n_frames)
%INSTANTANEOUS_FRAME_IDS Expand one configured frame range to output frames.

if ~(isstruct(settings) && isscalar(settings) && ...
        isfield(settings, 'frame_ids') && ...
        isfield(settings, 'n_output_frames'))
    error('tblR2:instantaneous_frame_ids:InvalidSettings', ...
        ['settings 必须包含 frame_ids=[first last]，且 n_output_frames 必须是' ...
        '正整数标量。']);
end
frame_range = settings.frame_ids;
n_output_frames = settings.n_output_frames;
valid_range = isnumeric(frame_range) && isreal(frame_range) && ...
    numel(frame_range) == 2 && all(isfinite(frame_range(:))) && ...
    all(frame_range(:) == fix(frame_range(:))) && ...
    frame_range(1) >= 1 && frame_range(2) >= frame_range(1) && ...
    frame_range(2) <= n_frames;
valid_count = isnumeric(n_output_frames) && isreal(n_output_frames) && ...
    isscalar(n_output_frames) && isfinite(n_output_frames) && ...
    n_output_frames == fix(n_output_frames) && n_output_frames >= 1;
if ~valid_range || ~valid_count || ...
        n_output_frames > frame_range(2) - frame_range(1) + 1
    error('tblR2:instantaneous_frame_ids:InvalidSettings', ...
        ['frame_ids 必须是位于 1:n_frames 内的有序整数边界，且 n_output_frames ' ...
        '不能超过包含端点的范围长度。']);
end

frame_range = double(reshape(frame_range, 1, 2));
frame_ids = floor(linspace(frame_range(1), frame_range(2), ...
    double(n_output_frames)));
frame_ids = unique(frame_ids, 'stable');
end
