function info = validate_sequence_cache(filename, cfg, source_role)
%VALIDATE_SEQUENCE_CACHE Read-only sequence metadata and coordinate contract.
% Used by Section 1 reuse/build completion and the independent Section 5
% entry. Never scans DAT, opens the other source, reads U/V/sampleValid, writes
% metadata, or rebuilds a cache. Source paths are identities: moving existing
% results requires a separately verified migration, not a silent path fix.
% Formal frame policy belongs to the calling section, not this reusable I/O
% check. The expected repeat count and boundaries come from cfg, not the file.

if nargin < 3 || isempty(source_role); source_role = 'raw'; end
source_role = validatestring(source_role, {'raw', 'postproc'});
required_cfg = {'case_id', 'sources', 'n_frames', 'fs', 'grid_size', 'frame_offset'};
missing_cfg = required_cfg(~isfield(cfg, required_cfg));
if ~isempty(missing_cfg) || ~isstruct(cfg.sources) || ...
        ~isfield(cfg.sources, source_role)
    error('tblR2:input:MissingCacheConfiguration', ...
        '缓存校验缺少 cfg 字段或 sources.%s：%s。请先运行 Section 0。', ...
        source_role, strjoin(missing_cfg, ', '));
end
validateattributes(cfg.n_frames, {'numeric'}, ...
    {'scalar', 'finite', 'integer', 'positive'}, mfilename, 'cfg.n_frames');
validateattributes(cfg.fs, {'numeric'}, ...
    {'scalar', 'finite', 'positive'}, mfilename, 'cfg.fs');
validateattributes(cfg.grid_size, {'numeric'}, ...
    {'vector', 'numel', 2, 'finite', 'integer', '>=', 2}, mfilename, 'cfg.grid_size');
wall_side = 'bottom';
if isfield(cfg, 'wall_side'); wall_side = char(cfg.wall_side); end

spec = cfg.sources.(source_role);
if isstruct(spec)
    if ~isscalar(spec) || ~all(isfield(spec, {'roots', 'offsets', 'ids'})) || ...
            ~iscellstr(spec.roots) || ~iscellstr(spec.ids) || ...
            numel(spec.roots) ~= 2 || numel(spec.offsets) ~= 2 || numel(spec.ids) ~= 2
        error('tblR2:input:InvalidRepeatSpec', ...
            'cfg.sources.%s 必须明确包含两个 roots、offsets 和 ids。', source_role);
    end
    roots = spec.roots(:).'; offsets = spec.offsets(:).'; ids = spec.ids(:).';
else
    % Preserve prepare_sequence_cache's explicit legacy single-repeat input.
    if ~(ischar(spec) || (isstring(spec) && isscalar(spec)))
        error('tblR2:input:InvalidRepeatSpec', 'cfg.sources.%s 不是源目录或 repeat 结构。', source_role);
    end
    roots = {char(spec)}; offsets = cfg.frame_offset; ids = {''};
end
validateattributes(offsets, {'numeric'}, ...
    {'vector', 'finite', 'integer', 'nonnegative'}, mfilename, 'repeat offsets');
n_repeats = numel(roots);
expected_total = n_repeats * double(cfg.n_frames);
expected_boundaries = [];
if n_repeats > 1; expected_boundaries = cfg.n_frames * (1:n_repeats-1); end
if isfield(cfg, 'total_frames') && ~isequal(double(cfg.total_frames), expected_total)
    mismatch('cfg.total_frames', cfg.total_frames, expected_total, filename);
end
if ~isfile(filename)
    error('tblR2:input:MissingCache', ...
        '所选 %s 缓存不存在：%s。请在 Section 1 compute 或放入已核实匹配的缓存。', ...
        source_role, filename);
end
required = {'U', 'V', 'sampleValid', 'X', 'Y', 'h_mm', 'frame_ids', ...
    'source_grid_size', 'j_wall_removed', 'cache_meta'};
inventory = whos('-file', filename);
names = {inventory.name};
missing = required(~ismember(required, names));
if ~isempty(missing)
    error('tblR2:input:InvalidCache', ...
        '缓存 %s 缺少 %s。请在 Section 1 compute，或读取完整且匹配的缓存。', ...
        filename, strjoin(missing, ', '));
end
small = load(filename, 'cache_meta', 'X', 'Y', 'h_mm', ...
    'frame_ids', 'source_grid_size', 'j_wall_removed');
meta = small.cache_meta;
meta_fields = {'schema_version', 'case_id', 'data_root', 'grid_size', ...
    'n_frames', 'total_frames', 'cached_size', 'fs', 'frame_offset', ...
    'source_first_file', 'source_last_file', 'source_role', 'source_root', ...
    'wall_side', 'y_mapping', 'repeat_ids', 'repeat_roots', 'repeat_offsets', ...
    'repeat_boundaries', 'repeat_means', 'precision'};
if ~isstruct(meta) || ~isscalar(meta)
    error('tblR2:input:CacheContractMismatch', ...
        '缓存 %s 的 cache_meta 必须为标量结构。请在 Section 1 compute 或读取匹配缓存。', filename);
end
meta_missing = meta_fields(~isfield(meta, meta_fields));
if ~isempty(meta_missing)
    error('tblR2:input:CacheContractMismatch', ...
        ['缓存 %s 缺少合同字段 %s；不能给旧缓存自动补身份。' ...
         '请在 Section 1 compute 或读取已核实匹配的缓存。'], filename, strjoin(meta_missing, ', '));
end
if ~strcmp(meta.source_role, source_role)
    error('tblR2:input:CacheSourceRoleMismatch', ...
        '缓存 %s 的 source_role=%s，当前选源=%s。请读取正确源缓存或在 Section 1 compute。', ...
        filename, meta.source_role, source_role);
end
expected = struct('schema_version', 4, 'case_id', cfg.case_id, ...
    'data_root', roots{1}, 'source_root', roots{1}, 'n_frames', cfg.n_frames, ...
    'total_frames', expected_total, 'fs', cfg.fs, 'frame_offset', offsets(1), ...
    'source_first_file', sprintf('B%04d.dat', offsets(1) + 1), ...
    'source_last_file', sprintf('B%04d.dat', offsets(1) + cfg.n_frames), ...
    'grid_size', cfg.grid_size, 'wall_side', wall_side, 'precision', 'single', ...
    'repeat_roots', {roots}, 'repeat_ids', {ids}, 'repeat_offsets', offsets, ...
    'repeat_boundaries', expected_boundaries);
fields = fieldnames(expected);
for k = 1:numel(fields)
    name = fields{k}; actual = meta.(name); value = expected.(name);
    if isnumeric(actual) && isnumeric(value)
        matches = isequal(double(actual), double(value));
    else
        matches = isequal(actual, value);
    end
    if ~matches; mismatch(['cache_meta.' name], actual, value, filename); end
end

u_item = inventory(strcmp(names, 'U'));
v_item = inventory(strcmp(names, 'V'));
mask_item = inventory(strcmp(names, 'sampleValid'));
u_size = u_item.size; u_size(end + 1:3) = 1;
v_size = v_item.size; v_size(end + 1:3) = 1;
mask_size = mask_item.size; mask_size(end + 1:3) = 1;
if ~isequal(u_size, v_size, mask_size) || numel(u_size) ~= 3 || u_size(1) ~= expected_total
    error('tblR2:input:InvalidCacheSize', ...
        '缓存 %s：U=%s、V=%s、sampleValid=%s；当前 cfg 要求总帧数 %d。请在 Section 1 compute 或读取匹配缓存。', ...
        filename, mat2str(u_size), mat2str(v_size), mat2str(mask_size), expected_total);
end
if ~strcmp(u_item.class, 'single') || ~strcmp(v_item.class, 'single') || ~strcmp(mask_item.class, 'logical')
    error('tblR2:input:InvalidCacheType', ...
        '缓存 %s 必须保存 single U/V 和 logical sampleValid；当前为 %s/%s/%s。', ...
        filename, u_item.class, v_item.class, mask_item.class);
end
J = u_size(2); I = u_size(3);
if ~isequal(double(meta.cached_size), double(u_size))
    mismatch('cache_meta.cached_size', meta.cached_size, u_size, filename);
end
if ~isequal(double(small.source_grid_size), double(cfg.grid_size))
    mismatch('source_grid_size', small.source_grid_size, cfg.grid_size, filename);
end
if ~(isnumeric(small.frame_ids) && isequal(size(small.frame_ids), [expected_total 1]) && ...
        isequal(double(small.frame_ids), (1:expected_total)'))
    error('tblR2:input:InvalidCacheSize', ...
        '缓存 %s 的 frame_ids 必须是列向量 1:%d。', filename, expected_total);
end
if ~isa(small.X, 'double') || ~isa(small.Y, 'double') || ...
        ~isequal(size(small.X), [J I]) || ~isequal(size(small.Y), [J I]) || ...
        any(~isfinite(small.X(:))) || any(~isfinite(small.Y(:))) || ...
        I ~= cfg.grid_size(1)
    error('tblR2:input:InvalidCacheCoordinates', ...
        '缓存 %s 的 X/Y 必须是有限 double [J I] 毫米网格，I 须匹配 cfg.grid_size(1)。', filename);
end
removed = small.j_wall_removed;
if ~(isnumeric(removed) && isscalar(removed) && isfinite(removed) && ...
        removed >= 0 && removed == fix(removed) && J + removed == cfg.grid_size(2))
    error('tblR2:input:InvalidCacheCoordinates', ...
        '缓存 %s 的 j_wall_removed 与源/缓存行数不匹配。', filename);
end
ym = meta.y_mapping;
if ~isstruct(ym) || ~isscalar(ym) || ...
        ~all(isfield(ym, {'version', 'method', 'h_y_mm'})) || ...
        ~isequal(double(ym.version), 1) || ...
        ~strcmp(ym.method, 'first_retained_row_0_plus_h') || ...
        ~(isnumeric(ym.h_y_mm) && isscalar(ym.h_y_mm) && isfinite(ym.h_y_mm) && ym.h_y_mm > 0)
    error('tblR2:input:InvalidCacheCoordinates', ...
        '缓存 %s 缺少合法的首保留行 0+h 壁面 Y 映射合同。', filename);
end
expected_y = repmat((1:J)' .* double(ym.h_y_mm), 1, I);
if any(abs(small.Y(:) - expected_y(:)) > 1e-9)
    error('tblR2:input:InvalidCacheCoordinates', ...
        '缓存 %s 的 Y 不符合记录的 y(j)=j*h_y 毫米映射。', filename);
end
if ~(isnumeric(small.h_mm) && isscalar(small.h_mm) && isfinite(small.h_mm) && small.h_mm > 0)
    error('tblR2:input:InvalidCacheCoordinates', '缓存 %s 的 h_mm 必须有限且为正。', filename);
end
repeat_size = size(meta.repeat_means); repeat_size(end + 1:4) = 1;
if ~isequal(repeat_size, [2 n_repeats J I])
    error('tblR2:input:InvalidCacheSize', ...
        '缓存 %s 的 repeat_means 尺寸应为 [2 %d %d %d]。不重算或修改其旧均值口径。', ...
        filename, n_repeats, J, I);
end
info = struct('filename', filename, 'size', u_size, 'n_frames', u_size(1), ...
    'J', J, 'I', I, 'X', small.X, 'Y', small.Y, 'h_mm', small.h_mm, ...
    'j_wall_removed', small.j_wall_removed, 'cache_meta', meta, ...
    'source_role', source_role, 'repeat_ids', {meta.repeat_ids}, ...
    'repeat_offsets', meta.repeat_offsets, 'repeat_boundaries', meta.repeat_boundaries, ...
    'repeat_means', meta.repeat_means);
end

function mismatch(field, actual, expected, filename)
% Report the actual field difference, never silently adopt or rewrite it.
error('tblR2:input:CacheContractMismatch', ...
    ['缓存 %s 的 %s 不匹配：缓存/当前值=%s，要求=%s。' ...
     '请检查 Section 0 的源与参数，并在 Section 1 compute 或读取匹配缓存。'], ...
    filename, field, jsonencode(actual), jsonencode(expected));
end
