function value = empty_frame_summary()
%EMPTY_FRAME_SUMMARY Typed frame/connectivity/sign count schema.
value = table(zeros(0,1,'uint32'), zeros(0,1,'uint32'), ...
    zeros(0,1,'int8'), zeros(0,1,'uint8'), zeros(0,1,'uint32'), ...
    zeros(0,1,'uint32'), zeros(0,1,'uint32'), zeros(0,1,'uint32'), ...
    zeros(0,1,'uint32'), zeros(0,1,'uint32'), zeros(0,1,'uint32'), ...
    'VariableNames', {'FrameOrdinal','FrameID','Sign','Connectivity', ...
    'ComponentCount','SS3Count','SS3p8Count','SS4p5Count', ...
    'CompleteSS3Count','CompleteSS3p8Count','CompleteSS4p5Count'});
end
