function [run_dir, manifest] = initialize_run(cfg, ctx)
%INITIALIZE_RUN Create or validate an isolated timestamped run directory.
config_hash = d23.config_hash(cfg);
if ~isempty(cfg.output.resume_run_dir)
    run_dir = char(cfg.output.resume_run_dir);
    manifest_file = fullfile(run_dir, 'manifest.mat');
    if ~isfile(manifest_file)
        error('d23:initialize_run:MissingManifest', ...
            'Resume directory lacks manifest.mat: %s', run_dir);
    end
    loaded = load(manifest_file, 'manifest');
    manifest = loaded.manifest;
    if ~strcmp(manifest.config_hash, config_hash) || ...
            ~strcmp(manifest.source_fingerprint, ctx.source_fingerprint)
        error('d23:initialize_run:ResumeMismatch', ...
            'Resume configuration or source fingerprint changed.');
    end
else
    if ~isfolder(cfg.output.root)
        mkdir(cfg.output.root);
    end
    stamp = char(datetime('now', 'TimeZone', 'UTC', ...
        'Format', 'yyyyMMdd_HHmmss_SSS'));
    token = char(java.util.UUID.randomUUID());
    run_name = sprintf('%s_%s_%s', stamp, cfg.execution.label, token(1:8));
    run_dir = fullfile(cfg.output.root, run_name);
    mkdir(run_dir);
    manifest = struct('schema_version', cfg.schema_version, ...
        'experiment_id', cfg.experiment_id, 'case_id', cfg.case_id, ...
        'run_label', cfg.execution.label, 'state', 'NEW', ...
        'config_hash', config_hash, ...
        'source_fingerprint', ctx.source_fingerprint, ...
        'ordered_frame_ordinals', double(cfg.execution.frame_ordinals(:)), ...
        'ordered_frame_ids', ctx.frame_ids(cfg.execution.frame_ordinals), ...
        'batch_size', cfg.statistics.chunk_size, ...
        'spatial_exclusion', ctx.spatial_exclusion, ...
        'matlab_release', version('-release'), ...
        'created_utc', d23.utc_now(), 'updated_utc', d23.utc_now());
    d23.atomic_save(fullfile(run_dir, 'manifest.mat'), struct('manifest', manifest));
    d23.atomic_write_text(fullfile(run_dir, 'config.json'), ...
        jsonencode(cfg, 'PrettyPrint', true));
end
folders = {'checkpoints', 'catalog_mat', 'catalog_csv', 'mat', 'csv', ...
    'json', 'md', 'fig', 'png', 'png/gallery', 'png/contact_sheets', 'pod'};
for i = 1:numel(folders)
    folder = fullfile(run_dir, folders{i});
    if ~isfolder(folder)
        mkdir(folder);
    end
end
end
