function geometry = structure_geometry(X_mm, Y_mm, delta_grid, dx_mm, dy_mm, pixels, sign_value, field)
%STRUCTURE_GEOMETRY Shared length/area/delta metrics for a connected component.
%   Optional FIELD (same size as X_mm) supplies the fluctuation values used
%   for the structure-internal mean (uMean) and peak amplitude (peakAmp);
%   when omitted or empty both are NaN (backwards compatible).

x_values = X_mm(pixels);
y_values = Y_mm(pixels);
delta_ref = median(delta_grid(pixels), 'omitnan');
length_x = max(x_values) - min(x_values) + dx_mm;
height_y = max(y_values) - min(y_values) + dy_mm;
area_mm2 = numel(pixels) * dx_mm * dy_mm;
if nargin >= 8 && ~isempty(field)
    vals = field(pixels);
    u_mean = mean(vals, 'omitnan');
    peak_amp = max(abs(vals), [], 'omitnan');
else
    u_mean = NaN;
    peak_amp = NaN;
end
geometry = struct('Sign', sign_value, 'PixelCount', numel(pixels), ...
    'Area_mm2', area_mm2, ...
    'CentroidX_mm', mean(x_values, 'omitnan'), ...
    'CentroidY_mm', mean(y_values, 'omitnan'), ...
    'XMin_mm', min(x_values), 'XMax_mm', max(x_values), ...
    'YMin_mm', min(y_values), 'YMax_mm', max(y_values), ...
    'LengthX_mm', length_x, 'HeightY_mm', height_y, ...
    'Delta99Ref_mm', delta_ref, ...
    'LengthX_over_delta', length_x / delta_ref, ...
    'HeightY_over_delta', height_y / delta_ref, ...
    'Area_over_delta2', area_mm2 / delta_ref ^ 2, ...
    'uMean', u_mean, 'peakAmp', peak_amp);
end
