% TEST_R2_LIBRARY_CONTRACT Static and light runtime checks for the shared core.
repo_root = fileparts(fileparts(mfilename('fullpath')));
case_root = fullfile(repo_root, 'cases', 'per_case', 'tandem_baseline_r2');
library_root = fullfile(repo_root, 'lib', '+tblR2');
assert(isfolder(library_root), 'Shared +tblR2 library is missing.');
assert(~isfolder(fullfile(library_root, '+r2')), ...
    'The compact library must not retain an extra +r2 package layer.');

required = {'prepare_sequence_cache', 'mean_stats_cache', 'mean_bl_friction', ...
    'assign_phase', 'phase_stats_cache', 'read_cache_frames', ...
    'structure_analysis_cache', ...
    'transport_analysis', 'temporal_spectra_cache', ...
    'spatial_spectra_cache', 'pod_module', 'pod_cache', ...
    'pod_reconstruction', 'dmd_module', 'dmd_cache', 'lcs_ftle', ...
    'plot_pod_products', 'plot_dmd_products', 'plot_lcs_ftle', 'spod_cache', ...
    'correlation_analysis_cache', 'streamwise_development_analysis', ...
    'plot_products', 'plot_core_products', 'figures_family', ...
    'figures_global', 'build_paths', ...
    'validate_config', 'save_result', ...
    'load_result'};
for k = 1:numel(required)
    assert(isfile(fullfile(library_root, [required{k} '.m'])), ...
        'Missing tblR2 core function: %s', required{k});
end

excluded = {'conditional_structure_average', 'conditional_spatial_spectra', ...
    'benchmark_structure_tracking', 'threshold_calibration_scan'};
for k = 1:numel(excluded)
    assert(~isfile(fullfile(library_root, [excluded{k} '.m'])), ...
        'Redundant r2 extension must stay out of the compact library: %s', ...
        excluded{k});
end
assert(~isfile(fullfile(library_root, '+bl', ...
    'composite_profile_sensitivity_kappa_b.m')), ...
    'The compact r2 library must not include the Option-B sensitivity grid.');
assert(isfile(fullfile(library_root, '+bl', 'data', 'Cf_chart.txt')), ...
    'The tblR2 log-law reference chart must be owned by the r2 library.');

structure_source = fileread(fullfile(library_root, 'structure_analysis_cache.m'));
for token = {'paper_proxy', 'vlsm_gallery', 'threshold_calibration', ...
        'conditional_structure_average', 'conditional_spatial_spectra', ...
        'benchmark_structure_tracking', 'sensitivity_scan'}
    assert(~contains(structure_source, token{1}), ...
        'Compact structure analysis contains excluded token: %s', token{1});
end
plot_source = fileread(fullfile(library_root, 'plot_products.m'));
assert(numel(regexp(structure_source, '\n')) + 1 < 800, ...
    'Compact structure analysis has grown beyond its intended size.');
assert(numel(regexp(plot_source, '\n')) + 1 < 500, ...
    'Compact plot layer has grown beyond its intended size.');

source = fileread(fullfile(case_root, 'tandem_baseline_r2_case.m'));
assert(~contains(source, 'run_case') && ~contains(source, 'run_section'), ...
    'r2 must not depend on workflow drivers.');
assert(~contains(source, 'stage_contract'), ...
    'r2 must not depend on the stage-contract framework.');
for token = {'paper_proxy', 'vlsm_gallery_count', 'threshold_calibration', ...
        'conditional_spectra', 'cfg.structures.tracking', ...
        'sensitivity_fractions'}
    assert(~contains(source, token{1}), ...
        'r2 case script contains excluded configuration: %s', token{1});
end

addpath(fullfile(repo_root, 'lib'), '-begin');
resolved = {'tblR2.validate_config', 'tblR2.mean_stats_cache', ...
    'tblR2.bl.loglaw_fit_chen', 'tblR2.io.load_tecplot_dat', ...
    'tblR2.stats.prepare_case_views', 'tblR2.wall.shear_momentum', ...
    'tblR2.pod.snapshot_decomposition', ...
    'tblR2.viz.export_publication_figure'};
for k = 1:numel(resolved)
    assert(startsWith(which(resolved{k}), [library_root filesep]), ...
        'MATLAB resolved %s outside the shared library.', resolved{k});
end
assert(isempty(which('tblR2.r2.validate_config')), ...
    'The obsolete tblR2.r2 package layer must not resolve.');
chart = tblR2.bl.load_cf_chart();
assert(isfield(chart, 'Cf_values') && ~isempty(chart.Cf_values), ...
    'The tblR2 log-law reference chart could not be loaded.');
paths = tblR2.build_paths(fullfile(tempdir, 'r2_library_contract_output'));
cleanup = onCleanup(@() rmdir(paths.root, 's'));
assert(contains(paths.phase, '03_phase_triple_statistics.mat'), ...
    'The r2 path contract must include the Section 3 phase artifact.');
cfg = struct('case_id', 'test/r2', 'case_type', 'baseline', ...
    'data_root', 'synthetic', 'n_frames', 2, 'total_frames', 4, ...
    'grid_size', [2 2], 'fs', 10);
value = struct('answer', 7);
tblR2.save_result(fullfile(paths.mat, 'value.mat'), value, cfg, 'smoke');
loaded = tblR2.load_result(fullfile(paths.mat, 'value.mat'), cfg, 'smoke');
assert(loaded.answer == 7, 'r2 result save/load smoke failed.');
clear cleanup
fprintf('test_r2_library_contract: PASS\n');
