% TEST_COMPACT_CASE_CONTRACT Static contract for the compact case entry.
repo_root = fileparts(fileparts(mfilename('fullpath')));
case_file = fullfile(repo_root, 'cases', 'per_case', ...
    'tandem_baseline_r2', 'tandem_baseline_r2_case.m');
assert(isfile(case_file), 'Compact case entry is missing.');
text = fileread(case_file);
required = { ...
    'cfg.case_id = ''per_case/tandem_baseline_r2'';', ...
    'bootstrap_r2_case(script_file)', ...
    'cfg.sources.raw', 'cfg.sources.postproc', ...
    'resolve_case_repeats', 'cfg.data_root = cfg.sources.raw.roots{1};', ...
    'cfg.total_frames = 2 * cfg.n_frames;', ...
    'tblR2.prepare_sequence_cache', ...
    'tblR2.mean_stats_cache', ...
    'tblR2.mean_bl_friction', ...
    'tblR2.phase_stats_cache', ...
    'tblR2.section4_vlsm_analysis', ...
    'tblR2.section5_run', ...
    'tblR2.temporal_spectra_cache', ...
    'tblR2.spatial_spectra_cache', ...
    'tblR2.pod_module', 'tblR2.dmd_module', 'tblR2.lcs_ftle', ...
    'tblR2.spod_cache', ...
    'tblR2.correlation_analysis_cache', ...
    'tblR2.streamwise_development_analysis', ...
    'tblR2.plot_products', ...
    'tblR2.save_result', 'tblR2.load_result', ...
    'cfg.phase = struct(''enabled'', false', ...
    'cfg.stages = struct();'};
for i = 1:numel(required)
    assert(contains(text, required{i}), ...
        'Compact entry is missing required token: %s', required{i});
end
assert(isfolder(fullfile(fileparts(case_file), 'lib', '+tblR2')), ...
    'Case entry must use its own local +tblR2 library.');
assert(~isfolder(fullfile(fileparts(case_file), '+tblR2')), ...
    'The case must not shadow the shared +tblR2 library.');
assert(contains(text, '正式计算至少需要'), ...
    'Compact entry must use a Chinese frame-count error message.');
assert(contains(text, 'paths.phase') && ...
    contains(text, 'tblR2.load_result(paths.phase, cfg, ''phase'', phase_inputs)') && ...
    contains(text, 'tblR2.save_result(paths.phase, results.phase, cfg, ''phase'', phase_inputs)'), ...
    'Compact entry must keep the complete phase compute/reuse/skip workflow.');
assert(~contains(text, 'Formal input requires') && ...
    ~contains(text, 'The raw cache is required'), ...
    'Compact entry still contains an English user-visible error message.');
assert(contains(text, '正式计算至少需要'), ...
    'Compact entry must use a Chinese frame-count error message.');
assert(~contains(text, 'Formal input requires') && ...
    ~contains(text, 'The raw cache is required'), ...
    'Compact entry still contains an English user-visible error message.');
assert(~contains(text, 'tbl.periodic.'), ...
    'Compact entry must not call the historical periodic package.');
assert(~contains(text, 'tblR2.run_case'), ...
    'Compact entry must expose the numerical order instead of run_case.');
assert(~contains(text, 'tblR2.run_section'), ...
    'Compact entry must not depend on the section wrapper.');
fprintf('test_compact_case_contract: PASS\n');
