% TEST_R2_STRUCTURE_CORE_SMOKE Exercise bounded structure recognition only.
repo_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(repo_root, 'lib'), '-begin');
root = tempname; mkdir(root); cleanup = onCleanup(@() rmdir(root, 's')); %#ok<NASGU>
I = 12; J = 8; n_frames = 16;
cache_file = fullfile(root, 'cache.mat');
U = single(zeros(n_frames, J, I)); V = single(zeros(n_frames, J, I));
sampleValid = true(n_frames, J, I);
for k = 1:n_frames
    [xx, yy] = meshgrid(1:I, 1:J);
    U(k,:,:) = single(0.2 * sin((xx + k) / 3) .* exp(-yy / 10));
    V(k,:,:) = single(0.1 * cos((xx - k) / 4) .* exp(-yy / 12));
end
X = repmat(1:I, J, 1); Y = repmat((1:J)', 1, I); h_mm = 1;
cache_meta = struct('schema_version',4,'case_id','test/r2/structure', 'source_role','postproc');
frame_ids = (1:n_frames)';
save(cache_file,'U','V','sampleValid','X','Y','h_mm','frame_ids','cache_meta','-v7.3');
stats = struct('X', X, 'Y', Y, 'h', h_mm, 'n_frames', n_frames, ...
    'accepted_mask', true(J,I), 'Uavex', squeeze(mean(U,1)), ...
    'Vavex', squeeze(mean(V,1)), 'u_rms', squeeze(std(double(U),0,1)), ...
    'v_rms', squeeze(std(double(V),0,1)), 'uv_rey', -squeeze(mean(double(U).*double(V),1)), ...
    'TKE', 0.5 * (squeeze(std(double(U),0,1)).^2 + squeeze(std(double(V),0,1)).^2), ...
    'repeat_means', []);
bl = struct('wall_distance_mm',Y,'boundary_layer',struct('x',1:I,'delta99',repmat(7,1,I)));
bl.normalization = struct('u_tau',1); bl.y_plus = Y;
cfg = struct('case_type','baseline','chunk_frames',4, ...
    'instantaneous',struct('frame_ids',[1 n_frames],'n_output_frames',2), ...
    'structures',struct('alpha',0.2,'seed_alpha',0.3,'min_pixels',2,'connectivity',8, ...
    'min_lsm_delta',1,'min_vlsm_delta',3,'max_wall_normal_delta',Inf, ...
    'catalog_frame_stride',2,'trusted_domain',struct('streamwise_edge_columns',1, ...
    'wall_normal_top_rows',1),'preprocessing',struct('enabled',false, ...
    'gaussian',struct('enabled',false)),'q2q4',struct('enabled',false, ...
    'H_values',[0 1],'frame_stride',2)));
structures = tblR2.structure_analysis_cache(cache_file,cfg,stats,[],bl);
assert(isfield(structures,'catalog') && isfield(structures,'instantaneous'));
assert(~isfield(structures,'vlsm_gallery') && ~isfield(structures,'sensitivity'));
fprintf('test_r2_structure_core_smoke: PASS\n');
