function summary = build_summary(ctx, detection_stats, collected, ...
    connectivity, pairs, spectra, cfg)
%BUILD_SUMMARY Compact machine/report summary with explicit denominators.
thresholds = cfg.detection.length_thresholds;
ss = collected.ss_catalog;
summary = struct();
summary.schema_version = 2;
summary.json_nonfinite_policy = 'MATLAB jsonencode emits JSON null; reason fields carry scientific absence';
summary.experiment_id = cfg.experiment_id;
summary.case_id = cfg.case_id;
summary.run_label = cfg.execution.label;
summary.created_utc = d23.utc_now();
summary.source = struct('cache_file', ctx.cache_file, ...
    'source_fingerprint', ctx.source_fingerprint, ...
    'utau_file', ctx.utau_source.path, ...
    'utau_result_created_utc', ctx.utau_source.meta.created_utc);
summary.scales = struct('u_tau_m_s', ctx.u_tau_m_s, ...
    'nu_m2_s', ctx.nu_m2_s, 'delta99_mm', ctx.delta99_mm, ...
    'u_edge_m_s', ctx.u_edge_m_s, 'Re_tau', ctx.Re_tau, ...
    'lower_limit_plus', ctx.lower_plus_limit, ...
    'upper_limit_plus', ctx.upper_plus_limit, ...
    'lower_spectrum_row', ctx.lower_spectrum_row, ...
    'upper_spectrum_row', ctx.upper_spectrum_row, ...
    'applicability_limited', ctx.applicability_limited, ...
    'applicability_note', ctx.applicability_note);
summary.preprocessing = struct('pod_enabled', cfg.preprocessing.pod.enabled, ...
    'gaussian_enabled', cfg.preprocessing.gaussian.enabled, ...
    'order', 'POD then Gaussian', ...
    'nominal_mode', ~cfg.preprocessing.pod.enabled && ...
    ~cfg.preprocessing.gaussian.enabled, ...
    'field_source', detection_stats.field_source);
summary.streamwise_edge_exclusion = cfg.detection.streamwise_edge_exclusion;
summary.streamwise_edge_exclusion.counts = struct([]);
summary.retention = struct('max_complete_ss_per_sign', ...
    double(cfg.detection.max_complete_ss_per_sign), ...
    'selection_rule', char(cfg.detection.selection_rule), ...
    'bbox_overlap_definition', 'shared_grid_pixel');
summary.spatial_exclusion = ctx.spatial_exclusion;
summary.spatial_exclusion.pod_retained_spatial_count_before_exclusion = ...
    double(detection_stats.pod_retained_spatial_count_before_exclusion);
summary.spatial_exclusion.pod_retained_spatial_count = ...
    double(detection_stats.pod_retained_spatial_count);
summary.spatial_exclusion.pod_excluded_retained_spatial_count = ...
    double(detection_stats.pod_excluded_retained_spatial_count);
summary.spatial_exclusion.pod_joint_dof_count = ...
    double(detection_stats.pod_joint_dof_count);
ratio = detection_stats.rms_ratio_to_postproc_same_domain_y;
ratio = ratio(isfinite(ratio));
if isempty(ratio)
    ratio_min = NaN; ratio_median = NaN; ratio_max = NaN;
else
    ratio_min = min(ratio); ratio_median = median(ratio); ratio_max = max(ratio);
end
summary.detection_statistics = struct( ...
    'field_source', detection_stats.field_source, ...
    'rms_definition', detection_stats.rms_definition, ...
    'pod_selected_rank', double(detection_stats.pod_selected_rank), ...
    'pod_positive_rank', double(detection_stats.pod_positive_rank), ...
    'pod_energy_target_fraction', ...
    detection_stats.pod_energy_target_fraction, ...
    'pod_joint_energy_retained_fraction', ...
    detection_stats.pod_joint_energy_retained_fraction, ...
    'u_energy_retained_fraction', detection_stats.u_energy_retained_fraction, ...
    'rms_ratio_min', ratio_min, 'rms_ratio_median', ratio_median, ...
    'rms_ratio_max', ratio_max);
summary.frames = struct('statistics_frames', 12000, ...
    'detected_frames', numel(cfg.execution.frame_ordinals), ...
    'batch_size', cfg.statistics.chunk_size, ...
    'catalog_rows', sum(double(collected.catalog_index.CatalogRowCount)));

counts = repmat(struct('connectivity', 0, 'length_threshold', 0, ...
    'all_ss', 0, 'complete_ss', 0, 'censored_ss', 0, ...
    'positive_complete', 0, 'negative_complete', 0, ...
    'frames_with_complete_ss', 0, ...
    'touching_user_exclusion_complete', 0, ...
    'touching_user_exclusion_fraction', NaN), 2 * numel(thresholds), 1);
slot = 0;
flag_names = {'IsSS3','IsSS3p8','IsSS4p5'};
for connectivity_value = cfg.detection.connectivities
    for k = 1:numel(thresholds)
        slot = slot + 1;
        selected = ss.Connectivity == connectivity_value & ss.(flag_names{k});
        complete = selected & ~ss.IsCensored;
        counts(slot).connectivity = connectivity_value;
        counts(slot).length_threshold = thresholds(k);
        counts(slot).all_ss = nnz(selected);
        counts(slot).complete_ss = nnz(complete);
        counts(slot).censored_ss = nnz(selected & ss.IsCensored);
        counts(slot).positive_complete = nnz(complete & ss.Sign == 1);
        counts(slot).negative_complete = nnz(complete & ss.Sign == -1);
        counts(slot).frames_with_complete_ss = numel(unique(ss.FrameOrdinal(complete)));
        touching = complete & ss.TouchesUserExclusion;
        counts(slot).touching_user_exclusion_complete = nnz(touching);
        if nnz(complete) > 0
            counts(slot).touching_user_exclusion_fraction = ...
                nnz(touching) / nnz(complete);
        end
    end
end
summary.counts = counts;

overlap = repmat(struct('length_threshold', 0, 'frames_8', 0, 'frames_4', 0, ...
    'intersection', 0, 'union', 0, 'jaccard', NaN, ...
    'fraction_8_also_4', NaN), numel(thresholds), 1);
for k = 1:numel(thresholds)
    selected8 = ss.Connectivity == 8 & ss.(flag_names{k}) & ~ss.IsCensored;
    selected4 = ss.Connectivity == 4 & ss.(flag_names{k}) & ~ss.IsCensored;
    frames8 = unique(ss.FrameOrdinal(selected8));
    frames4 = unique(ss.FrameOrdinal(selected4));
    both = intersect(frames8, frames4);
    either = union(frames8, frames4);
    overlap(k).length_threshold = thresholds(k);
    overlap(k).frames_8 = numel(frames8);
    overlap(k).frames_4 = numel(frames4);
    overlap(k).intersection = numel(both);
    overlap(k).union = numel(either);
    if ~isempty(either)
        overlap(k).jaccard = numel(both) / numel(either);
    end
    if ~isempty(frames8)
        overlap(k).fraction_8_also_4 = numel(both) / numel(frames8);
    end
end
summary.connectivity_frame_overlap = overlap;
summary.connectivity_frame_sign_comparison = ...
    table2struct(connectivity.summary_table);
length_distribution = d23.connectivity_length_distribution(ss);
summary.connectivity_length_statistics = length_distribution.statistics;
summary.matching = struct('eligible_complete_primary_ss', height(pairs), ...
    'matched_pairs', nnz(pairs.Matched), ...
    'unmatched_pairs', nnz(~pairs.Matched));
summary.spectra = struct('rows', height(spectra.spectra_table), ...
    'energy_rows', height(spectra.energy_table), ...
    'description', spectra.definition);

performance = collected.frame_performance;
summary.performance = performance_summary(performance);
end

function output = performance_summary(performance)
if isempty(performance)
    output = struct('n_frames', 0);
    return;
end
elapsed = performance.Elapsed_s;
finite_memory = performance.MatlabMemoryBytes(isfinite(performance.MatlabMemoryBytes));
output = struct('n_frames', height(performance), ...
    'mean_seconds_per_frame', mean(elapsed), ...
    'median_seconds_per_frame', median(elapsed), ...
    'p95_seconds_per_frame', prctile(elapsed, 95), ...
    'measured_total_seconds', sum(elapsed), ...
    'estimated_12000_frame_seconds', mean(elapsed) * 12000, ...
    'peak_matlab_memory_bytes', NaN);
if ~isempty(finite_memory)
    output.peak_matlab_memory_bytes = max(finite_memory);
end
gaps = [true; diff(double(performance.FrameOrdinal)) ~= 1];
segment_id = cumsum(gaps);
segments = repmat(struct('segment',0,'first_frame',0,'last_frame',0, ...
    'n_frames',0,'mean_seconds_per_frame',NaN,'component_count',0), ...
    max(segment_id), 1);
for s = 1:max(segment_id)
    rows = segment_id == s;
    segments(s).segment = s;
    segments(s).first_frame = double(performance.FrameOrdinal(find(rows,1,'first')));
    segments(s).last_frame = double(performance.FrameOrdinal(find(rows,1,'last')));
    segments(s).n_frames = nnz(rows);
    segments(s).mean_seconds_per_frame = mean(elapsed(rows));
    segments(s).component_count = sum(double(performance.ComponentCount(rows)));
end
output.contiguous_segments = segments;
end
