function value = empty_catalog()
%EMPTY_CATALOG Typed zero-row schema for all connected components.
value = table(zeros(0,1,'uint32'), zeros(0,1,'uint32'), ...
    zeros(0,1,'int8'), zeros(0,1,'uint8'), zeros(0,1,'uint32'), ...
    zeros(0,1,'uint32'), zeros(0,1), zeros(0,1), zeros(0,1), zeros(0,1), ...
    zeros(0,1,'uint16'), zeros(0,1,'uint16'), ...
    zeros(0,1,'uint16'), zeros(0,1,'uint16'), ...
    zeros(0,1), zeros(0,1), zeros(0,1), zeros(0,1), ...
    zeros(0,1), zeros(0,1), zeros(0,1), zeros(0,1), zeros(0,1), zeros(0,1), ...
    false(0,1), false(0,1), false(0,1), ...
    false(0,1), false(0,1), ...
    false(0,1), false(0,1), false(0,1), ...
    false(0,1), false(0,1), false(0,1), false(0,1), false(0,1), ...
    false(0,1), false(0,1), zeros(0,1,'uint8'), ...
    false(0,1), false(0,1), false(0,1), false(0,1), ...
    'VariableNames', {'FrameOrdinal','FrameID','Sign','Connectivity', ...
    'ComponentID','PixelCount','BBoxX_px','BBoxY_px','BBoxWidth_px', ...
    'BBoxHeight_px','ColMin','ColMax','RowMin','RowMax','XMin_mm', ...
    'XMax_mm','YMin_mm','YMax_mm','Area_mm2','FillFraction', ...
    'Lx_mm','Lx_over_delta','YMin_plus','YMax_plus', ...
    'PassLength3','PassLength3p8','PassLength4p5','PassWallLower', ...
    'PassWallUpper','IsSS3','IsSS3p8','IsSS4p5','TouchesUpstream', ...
    'TouchesDownstream','TouchesWall','TouchesTop','TouchesInvalid', ...
    'TouchesUserExclusion', ...
    'IsCensored','CensorReasonCode', ...
    'TouchesStreamwiseLeftBuffer','TouchesStreamwiseRightBuffer', ...
    'RejectedByStreamwiseEdge','SuppressedByBBoxOverlap'});
end
