function [mask, info] = resolve_spatial_exclusion(X_mm, wall_distance_mm, options)
%RESOLVE_SPATIAL_EXCLUSION Map a user rectangle onto measured cell centers.
if ~isequal(size(X_mm), size(wall_distance_mm)) || ~ismatrix(X_mm)
    error('d23:resolve_spatial_exclusion:GridShape', ...
        'X_mm and wall_distance_mm must be equal-size 2-D grids.');
end
mask = false(size(X_mm));
info = struct('schema_version', 1, 'enabled', logical(options.enabled), ...
    'coordinate_system', 'x_mm_and_wall_distance_mm_cell_centers', ...
    'interval_semantics', 'closed', ...
    'requested_x_start_mm', empty_or_double(options.x_start_mm), ...
    'requested_x_end_mm', empty_or_double(options.x_end_mm), ...
    'requested_wall_y_start_mm', 0, ...
    'requested_wall_y_height_mm', empty_or_double(options.wall_y_height_mm), ...
    'realized_x_min_mm', NaN, 'realized_x_max_mm', NaN, ...
    'realized_wall_y_min_mm', NaN, 'realized_wall_y_max_mm', NaN, ...
    'row_indices', zeros(0,1,'uint16'), ...
    'column_indices', zeros(0,1,'uint16'), ...
    'excluded_grid_point_count', uint32(0), ...
    'active_grid_point_count', uint32(numel(X_mm)), ...
    'mask_hash', d23.sha256_text('disabled'));
if ~info.enabled
    return;
end

x0 = double(options.x_start_mm);
x1 = double(options.x_end_mm);
y1 = double(options.wall_y_height_mm);
mask = isfinite(X_mm) & isfinite(wall_distance_mm) & ...
    X_mm >= x0 & X_mm <= x1 & ...
    wall_distance_mm >= 0 & wall_distance_mm <= y1;
if ~any(mask, 'all')
    error('d23:resolve_spatial_exclusion:NoIntersection', ...
        ['Requested spatial exclusion [%.9g, %.9g] mm x [0, %.9g] mm ' ...
        'does not contain any measured grid center.'], x0, x1, y1);
end
[rows, columns] = find(mask);
x_values = double(X_mm(mask));
y_values = double(wall_distance_mm(mask));
info.realized_x_min_mm = min(x_values);
info.realized_x_max_mm = max(x_values);
info.realized_wall_y_min_mm = min(y_values);
info.realized_wall_y_max_mm = max(y_values);
info.row_indices = uint16(unique(rows));
info.column_indices = uint16(unique(columns));
info.excluded_grid_point_count = uint32(nnz(mask));
info.active_grid_point_count = uint32(numel(mask) - nnz(mask));
info.mask_hash = d23.sha256_text(jsonencode(uint32(find(mask))));
end

function value = empty_or_double(value)
if isempty(value)
    value = [];
else
    value = double(value);
end
end
