function validate_dual_source_grid(raw_file, postproc_file)
%VALIDATE_DUAL_SOURCE_GRID Ensure raw and PostProc caches use one grid.

if ~isfile(raw_file) || ~isfile(postproc_file)
    error('tblR2:input:MissingDualSourceCache', ...
        'raw 和 postproc 序列缓存必须同时存在。');
end
raw = load(raw_file, 'X', 'Y', 'j_wall_removed', 'cache_meta');
post = load(postproc_file, 'X', 'Y', 'j_wall_removed', 'cache_meta');
if raw.cache_meta.frame_offset ~= post.cache_meta.frame_offset || ...
        ~isequal(size(raw.X), size(post.X)) || ~isequal(size(raw.Y), size(post.Y)) || ...
        max(abs(raw.X(:) - post.X(:)), [], 'omitnan') > 1e-9 || ...
        max(abs(raw.Y(:) - post.Y(:)), [], 'omitnan') > 1e-9 || ...
        raw.j_wall_removed ~= post.j_wall_removed
    error('tblR2:input:DualSourceGridMismatch', ...
        'raw 与 PostProc 缓存必须共享 X、Y、壁面裁剪和帧偏移。');
end
end
