function [theta_used, diag] = select_secant_theta( ...
        theta_raw, x, source, p, gap_mode, contamination_x)
%SELECT_SECANT_THETA 为system/calibration secant统一选择theta数据来源。
% source='raw'      ：直接使用首站位掩膜后的原始theta；
% source='p_smooth' ：使用与local Cf相同的p平滑theta。contamination_x=[]
% 表示不人为删除任何流向区间；非空区间仅保留给旧工作流兼容。

if nargin < 6
    error('tblR2:wall:select_secant_theta:MissingOptions', ...
        ['必须显式提供 source、p、gap_mode 和 contamination_x。']);
end
if ~isnumeric(theta_raw) || ~isreal(theta_raw) || ~isvector(theta_raw) || ...
        ~isnumeric(x) || ~isreal(x) || ~isvector(x) || ...
        ~isequal(size(theta_raw), size(x))
    error('tblR2:wall:select_secant_theta:SizeMismatch', ...
        'theta_raw 和 x 必须是尺寸相同的实数数值向量。');
end
if ~(ischar(source) || (isstring(source) && isscalar(source)))
    error('tblR2:wall:select_secant_theta:InvalidSource', ...
        'source 必须是 ''raw'' 或 ''p_smooth''。');
end
source = lower(char(source));
if ~ismember(source, {'raw', 'p_smooth'})
    error('tblR2:wall:select_secant_theta:InvalidSource', ...
        'source 必须是 ''raw'' 或 ''p_smooth''。');
end
gap_mode = lower(char(gap_mode));
if ~ismember(gap_mode, {'separate_segments', 'bridge_contamination'})
    error('tblR2:wall:select_secant_theta:InvalidGapMode', ...
        'gap_mode 必须是 ''separate_segments'' 或 ''bridge_contamination''。');
end
contamination_x = reshape(contamination_x, 1, []);
if ~isempty(contamination_x) && (numel(contamination_x) ~= 2 || ...
        any(~isfinite(contamination_x)) || ...
        contamination_x(2) <= contamination_x(1))
    error('tblR2:wall:select_secant_theta:InvalidContamination', ...
        ['contamination_x 必须为空（关闭），或为有限且递增的 [x_min x_max] 区间。']);
end

if strcmp(source, 'raw')
    theta_used = theta_raw;
    smoothing_diag = struct( ...
        'gap_mode', gap_mode, ...
        'pre_smooth_p', p, ...
        'contamination_x', contamination_x, ...
        'fit_mask', false(size(theta_raw)), ...
        'upstream_fit_mask', false(size(theta_raw)), ...
        'downstream_fit_mask', false(size(theta_raw)), ...
        'fit_sample_count', 0, ...
        'pollution_interpolation_mask', false(size(theta_raw)), ...
        'fit_segments_index', zeros(0, 2), ...
        'fit_segments_x', zeros(0, 2), ...
        'method', 'raw theta; no smoothing');
else
    opts = struct('gap_mode', gap_mode, ...
        'contamination_x', contamination_x);
    [theta_used, smoothing_diag] = ...
        tblR2.wall.smooth_streamwise_series(theta_raw, x, p, opts);
end

diag = smoothing_diag;
diag.theta_source = source;
diag.theta_raw = theta_raw;
diag.theta_used = theta_used;
diag.valid_mask_used = isfinite(theta_used);
diag.smoothing_applied = strcmp(source, 'p_smooth');
end
