function value = empty_pairs()
%EMPTY_PAIRS Typed matched-noSS audit schema.
value = table(zeros(0,1,'uint32'), zeros(0,1,'uint32'), zeros(0,1,'uint32'), ...
    zeros(0,1,'int8'), zeros(0,1,'uint32'), zeros(0,1), ...
    false(0,1), false(0,1), false(0,1), ...
    zeros(0,1,'uint16'), zeros(0,1,'uint16'), ...
    zeros(0,1,'uint16'), zeros(0,1,'uint16'), ...
    zeros(0,1,'uint16'), zeros(0,1,'uint16'), ...
    zeros(0,1), zeros(0,1), false(0,1), ...
    zeros(0,1,'uint8'), zeros(0,1,'uint32'), ...
    'VariableNames', {'PairID','FrameOrdinal','FrameID','Sign','ComponentID', ...
    'Lx_over_delta','PassLength3','PassLength3p8','PassLength4p5', ...
    'SSColMin','SSColMax','RowMin','RowMax','NoSSColMin','NoSSColMax', ...
    'CenterShift_cells','CenterShift_mm','Matched','NoSSReasonCode', ...
    'CandidateCount'});
end
