function value = summarize_frame(catalog, frame_ordinal, frame_id, sign_value, connectivity)
%SUMMARIZE_FRAME One row of counts for a sign/connectivity threshold field.
value = table(uint32(frame_ordinal), uint32(frame_id), int8(sign_value), ...
    uint8(connectivity), uint32(height(catalog)), uint32(nnz(catalog.IsSS3)), ...
    uint32(nnz(catalog.IsSS3p8)), uint32(nnz(catalog.IsSS4p5)), ...
    uint32(nnz(catalog.IsSS3 & ~catalog.IsCensored)), ...
    uint32(nnz(catalog.IsSS3p8 & ~catalog.IsCensored)), ...
    uint32(nnz(catalog.IsSS4p5 & ~catalog.IsCensored)), ...
    'VariableNames', d23.empty_frame_summary().Properties.VariableNames);
end
