function validate_config(cfg)
%VALIDATE_CONFIG Fail closed on ambiguous scientific or runtime settings.
required = {'data', 'statistics', 'detection', 'preprocessing', ...
    'matching', 'spectra', 'execution', 'output'};
if ~all(isfield(cfg, required))
    error('d23:validate_config:MissingSection', ...
        'Configuration is missing a required section.');
end
if ~isscalar(cfg.statistics.chunk_size) || ...
        ~isfinite(cfg.statistics.chunk_size) || cfg.statistics.chunk_size ~= 48
    error('d23:validate_config:ChunkContract', ...
        'This experiment requires an exact 48-frame chunk size.');
end
if ~isequal(double(cfg.detection.connectivities(:).'), [8 4]) || ...
        cfg.detection.primary_connectivity ~= 8
    error('d23:validate_config:ConnectivityContract', ...
        'The primary/sensitivity connectivity contract must be [8 4].');
end
if ~isequal(double(cfg.detection.length_thresholds(:).'), [3 3.8 4.5]) || ...
        cfg.detection.amplitude_multiplier ~= 1
    error('d23:validate_config:ThresholdContract', ...
        'Locked amplitude and length thresholds were changed.');
end
limit = double(cfg.detection.max_complete_ss_per_sign);
valid_limit = isscalar(limit) && (isinf(limit) || ...
    (isfinite(limit) && limit >= 1 && limit == fix(limit)));
valid_rules = {'longest_then_pixel_count_then_component_id', ...
    'longest_then_pixel_count_then_component_id_nonoverlapping_bbox'};
if ~valid_limit || ~isfield(cfg.detection, 'selection_rule') || ...
        ~ismember(char(cfg.detection.selection_rule), valid_rules)
    error('d23:validate_config:PerSignLimit', ...
        ['max_complete_ss_per_sign must be a positive integer or Inf, and ' ...
        'selection_rule must be a supported deterministic retention rule.']);
end
if ~isfield(cfg.detection, 'streamwise_edge_exclusion') || ...
        ~isstruct(cfg.detection.streamwise_edge_exclusion) || ...
        ~isscalar(cfg.detection.streamwise_edge_exclusion)
    error('d23:validate_config:StreamwiseEdgeExclusion', ...
        'detection.streamwise_edge_exclusion must be a scalar struct.');
end
edge = cfg.detection.streamwise_edge_exclusion;
if ~all(isfield(edge, {'enabled','buffer_cells'})) || ...
        ~isscalar(edge.enabled) || ...
        ~(islogical(edge.enabled) || isnumeric(edge.enabled)) || ...
        ~isfinite(double(edge.enabled)) || ...
        ~ismember(double(edge.enabled), [0 1]) || ...
        ~isscalar(edge.buffer_cells) || ~isfinite(double(edge.buffer_cells)) || ...
        double(edge.buffer_cells) < 0 || ...
        double(edge.buffer_cells) ~= fix(double(edge.buffer_cells))
    error('d23:validate_config:StreamwiseEdgeExclusion', ...
        ['streamwise_edge_exclusion requires a logical enabled flag and a ' ...
        'nonnegative integer buffer_cells.']);
end
if ~strcmp(cfg.spectra.window, 'hamming_periodic') || ...
        cfg.spectra.zero_padding_factor ~= 4
    error('d23:validate_config:SpectrumContract', ...
        'The spectrum requires periodic Hamming and fourfold zero padding.');
end
frames = double(cfg.execution.frame_ordinals(:));
if isempty(frames) || any(~isfinite(frames)) || any(frames ~= fix(frames)) || ...
        any(frames < 1) || numel(unique(frames)) ~= numel(frames)
    error('d23:validate_config:InvalidFrames', ...
        'Execution frame ordinals must be unique positive integers.');
end

if ~isfield(cfg.preprocessing, 'spatial_exclusion') || ...
        ~isstruct(cfg.preprocessing.spatial_exclusion) || ...
        ~isscalar(cfg.preprocessing.spatial_exclusion)
    error('d23:validate_config:SpatialExclusion', ...
        'preprocessing.spatial_exclusion must be a scalar struct.');
end
exclusion = cfg.preprocessing.spatial_exclusion;
required_exclusion = {'enabled','x_start_mm','x_end_mm','wall_y_height_mm'};
if ~all(isfield(exclusion, required_exclusion)) || ...
        ~isscalar(exclusion.enabled) || ...
        ~(islogical(exclusion.enabled) || isnumeric(exclusion.enabled)) || ...
        ~isfinite(double(exclusion.enabled)) || ...
        ~ismember(double(exclusion.enabled), [0 1])
    error('d23:validate_config:SpatialExclusion', ...
        'Spatial exclusion requires a scalar logical enabled flag and all bounds.');
end
if logical(exclusion.enabled)
    values = [exclusion.x_start_mm exclusion.x_end_mm exclusion.wall_y_height_mm];
    if numel(values) ~= 3 || any(~isfinite(double(values))) || ...
            ~all(arrayfun(@isscalar, values)) || ...
            exclusion.x_start_mm > exclusion.x_end_mm || ...
            exclusion.wall_y_height_mm < 0
        error('d23:validate_config:SpatialExclusionBounds', ...
            ['Enabled spatial exclusion requires finite scalar x_start_mm <= ' ...
            'x_end_mm and wall_y_height_mm >= 0.']);
    end
end

pod = cfg.preprocessing.pod;
if pod.enabled
    if ~strcmp(pod.rms_source, 'reconstruction')
        error('d23:validate_config:PodRmsSource', ...
            'POD detection RMS must be recomputed from the reconstruction.');
    end
    if isempty(pod.min_valid_fraction) || ~isscalar(pod.min_valid_fraction) || ...
            ~isfinite(pod.min_valid_fraction) || ...
            pod.min_valid_fraction <= 0 || pod.min_valid_fraction > 1
        error('d23:validate_config:PodValidity', ...
            'Enabled POD requires explicit 0 < min_valid_fraction <= 1.');
    end
    if ~isstruct(pod.rank) || ~isscalar(pod.rank) || ...
            ~isfield(pod.rank, 'kind')
        error('d23:validate_config:PodRank', ...
            'Enabled POD requires an explicit rank.kind.');
    end
    kind = char(pod.rank.kind);
    switch kind
        case 'fixed_n'
            if ~isfield(pod.rank, 'n') || isfield(pod.rank, 'value') || ...
                    ~isscalar(pod.rank.n) || ~isfinite(pod.rank.n) || ...
                    pod.rank.n < 1 || ...
                    pod.rank.n ~= fix(pod.rank.n)
                error('d23:validate_config:PodRank', ...
                    'fixed_n requires only a positive integer rank.n.');
            end
        case 'energy_fraction'
            if ~isfield(pod.rank, 'value') || isfield(pod.rank, 'n') || ...
                    ~isscalar(pod.rank.value) || ~isfinite(pod.rank.value) || ...
                    pod.rank.value <= 0 || ...
                    pod.rank.value > 1
                error('d23:validate_config:PodRank', ...
                    'energy_fraction requires only 0 < rank.value <= 1.');
            end
        otherwise
            error('d23:validate_config:PodRank', ...
                'rank.kind must be fixed_n or energy_fraction.');
    end
end
gaussian = cfg.preprocessing.gaussian;
if gaussian.enabled && (isempty(gaussian.sigma_cells) || ...
        ~isscalar(gaussian.sigma_cells) || gaussian.sigma_cells <= 0 || ...
        ~isfinite(gaussian.sigma_cells))
    error('d23:validate_config:GaussianSigma', ...
        'Enabled Gaussian preprocessing requires explicit positive sigma_cells.');
end
if ~strcmp(cfg.output.field_colormap, 'balance') || ...
        cfg.output.field_colormap_levels ~= 257 || ...
        ~isequal(double(cfg.output.field_clim(:).'), [-3 3]) || ...
        ~cfg.output.field_physical_aspect
    error('d23:validate_config:FieldFigureContract', ...
        'Field figures require balance(257), symmetric [-3 3], and 1:1 units.');
end
end
