function write_outputs(ctx, stats, detection_stats, collected, connectivity, ...
    pairs, spectra, selection, summary, cfg, run_dir, figure_files, gallery_files)
%WRITE_OUTPUTS Publish final MAT/CSV/JSON/Markdown artifacts.
connectivity_length_distribution = ...
    d23.connectivity_length_distribution(collected.ss_catalog);
rms_profile = table(ctx.wall_y_mm, stats.u_rms_y, ...
    detection_stats.postproc_same_domain_u_rms_y, detection_stats.u_rms_y, ...
    detection_stats.rms_ratio_to_postproc_same_domain_y, ...
    detection_stats.valid_count_y, ...
    'VariableNames', {'WallDistance_mm','PostProcURms_m_s', ...
    'PostProcSameDomainURms_m_s','ActiveFieldURms_m_s', ...
    'ActiveToPostProcSameDomainRatio','ActiveValidCount'});
d23.atomic_save(fullfile(run_dir, 'mat', 'final_results.mat'), struct( ...
    'context', ctx, 'statistics', stats, ...
    'detection_statistics', detection_stats, ...
    'detection_rms_profile', rms_profile, ...
    'frame_summary', collected.frame_summary, ...
    'frame_performance', collected.frame_performance, ...
    'ss_catalog', collected.ss_catalog, ...
    'censored_ss_catalog', collected.censored_ss_catalog, ...
    'complete_ss_catalog', collected.complete_ss_catalog, ...
    'catalog_index', collected.catalog_index, 'noss_pairs', pairs, ...
    'conditional_spectra', spectra, 'gallery_selection', selection, ...
    'connectivity_comparison', connectivity, ...
    'connectivity_length_distribution', connectivity_length_distribution, ...
    'summary', summary, 'config', cfg, ...
    'summary_figure_files', figure_files, 'gallery_files', gallery_files));
d23.atomic_writetable(fullfile(run_dir, 'csv', 'noss_pairs.csv'), pairs);
d23.atomic_writetable(fullfile(run_dir, 'csv', 'conditional_spectra.csv'), ...
    spectra.spectra_table);
d23.atomic_writetable(fullfile(run_dir, 'csv', 'large_scale_energy.csv'), ...
    spectra.energy_table);
d23.atomic_writetable(fullfile(run_dir, 'csv', 'gallery_selection.csv'), selection);
d23.atomic_writetable(fullfile(run_dir, 'csv', ...
    'connectivity_length_distribution.csv'), ...
    connectivity_length_distribution.table);
d23.atomic_writetable(fullfile(run_dir, 'csv', ...
    'connectivity_frame_sign_comparison.csv'), connectivity.frame_sign_table);
d23.atomic_writetable(fullfile(run_dir, 'csv', ...
    'connectivity_paired_objects.csv'), connectivity.paired_table);
d23.atomic_writetable(fullfile(run_dir, 'csv', ...
    'connectivity_comparison_summary.csv'), connectivity.summary_table);
d23.atomic_writetable(fullfile(run_dir, 'csv', 'detection_rms_profile.csv'), ...
    rms_profile);
d23.atomic_writetable(fullfile(run_dir, 'csv', 'reference_profile.csv'), ...
    ctx.reference_profile);
d23.atomic_write_text(fullfile(run_dir, 'json', 'summary.json'), ...
    jsonencode(summary, 'PrettyPrint', true));
source_manifest = struct('schema_version', 1, 'cache', ctx.cache_source, ...
    'utau_result', ctx.utau_source, 'source_fingerprint', ctx.source_fingerprint, ...
    'actual_u_tau_m_s', ctx.u_tau_m_s, 'delta99_mm', ctx.delta99_mm, ...
    'Re_tau', ctx.Re_tau, 'active_field_source', detection_stats.field_source, ...
    'spatial_exclusion', ctx.spatial_exclusion, ...
    'active_rms_definition', detection_stats.rms_definition, ...
    'created_utc', d23.utc_now());
d23.atomic_write_text(fullfile(run_dir, 'json', 'source_manifest.json'), ...
    jsonencode(source_manifest, 'PrettyPrint', true));
d23.atomic_write_text(fullfile(run_dir, 'md', 'report.md'), ...
    markdown_report(summary, spectra, selection));
end

function text_value = markdown_report(summary, spectra, selection)
lines = strings(0,1);
lines(end+1) = "# Deshpande et al. (2023) SS 识别报告";
lines(end+1) = "";
lines(end+1) = "## 运行与尺度";
lines(end+1) = "";
lines(end+1) = sprintf('- 运行类型：`%s`', summary.run_label);
lines(end+1) = sprintf('- 识别场：`%s`', ...
    summary.detection_statistics.field_source);
lines(end+1) = sprintf('- 统计帧数：%d；识别帧数：%d；分块：%d 帧', ...
    summary.frames.statistics_frames, summary.frames.detected_frames, ...
    summary.frames.batch_size);
lines(end+1) = sprintf('- u_tau = %.9g m/s（动态读取当前 r2 结果）', ...
    summary.scales.u_tau_m_s);
lines(end+1) = sprintf('- delta99 = %.6g mm；Re_tau = %.6g', ...
    summary.scales.delta99_mm, summary.scales.Re_tau);
lines(end+1) = sprintf('- 预处理：POD=%d，Gaussian=%d；执行顺序固定为 POD → Gaussian', ...
    summary.preprocessing.pod_enabled, summary.preprocessing.gaussian_enabled);
lines(end+1) = sprintf('- RMS 判据：%s', ...
    summary.detection_statistics.rms_definition);
if summary.spatial_exclusion.enabled
    lines(end+1) = sprintf(['- 用户空间排除区：x=[%.6g, %.6g] mm，' ...
        'y_wall=[0, %.6g] mm；实际排除 %d 个网格点。'], ...
        summary.spatial_exclusion.requested_x_start_mm, ...
        summary.spatial_exclusion.requested_x_end_mm, ...
        summary.spatial_exclusion.requested_wall_y_height_mm, ...
        summary.spatial_exclusion.excluded_grid_point_count);
    lines(end+1) = sprintf(['- POD retained spatial DOF：%d -> %d；' ...
        '联合 u/v DOF：%d。'], ...
        summary.spatial_exclusion.pod_retained_spatial_count_before_exclusion, ...
        summary.spatial_exclusion.pod_retained_spatial_count, ...
        summary.spatial_exclusion.pod_joint_dof_count);
else
    lines(end+1) = '- 用户空间排除区：disabled。';
end
if isinf(summary.retention.max_complete_ss_per_sign)
    retention_limit = 'all non-overlapping';
else
    retention_limit = sprintf('%d', summary.retention.max_complete_ss_per_sign);
end
lines(end+1) = sprintf(['- 每个 frame × connectivity × sign 最多保留 %s 个完整 SS；' ...
    '选择规则：最长 Lx/delta → 最大像素数 → 最小组件 ID；' ...
    '包围盒共享至少一个网格像素时只保留较长对象。'], retention_limit);
if summary.streamwise_edge_exclusion.enabled
    lines(end+1) = sprintf(['- 流向边缘排除：enabled；距左/右 FOV 边缘不超过 %d ' ...
        '个网格点的候选不会成为 VLSM。'], ...
        summary.streamwise_edge_exclusion.buffer_cells);
else
    lines(end+1) = sprintf('- 流向边缘排除：disabled（配置缓冲 %d 个网格点）。', ...
        summary.streamwise_edge_exclusion.buffer_cells);
end
if summary.preprocessing.pod_enabled
    lines(end+1) = sprintf(['- POD 选中阶数：%d / 正数值秩 %d；联合能量保留 %.6g；' ...
        'u 能量保留 %.6g。'], ...
        summary.detection_statistics.pod_selected_rank, ...
        summary.detection_statistics.pod_positive_rank, ...
        summary.detection_statistics.pod_joint_energy_retained_fraction, ...
        summary.detection_statistics.u_energy_retained_fraction);
    lines(end+1) = sprintf(['- POD/PostProc 同域 RMS 比：min %.6g，median %.6g，' ...
        'max %.6g。'], summary.detection_statistics.rms_ratio_min, ...
        summary.detection_statistics.rms_ratio_median, ...
        summary.detection_statistics.rms_ratio_max);
end
if summary.scales.applicability_limited
    lines(end+1) = sprintf('- **适用性警告：%s**', summary.scales.applicability_note);
end
lines(end+1) = "";
lines(end+1) = "## SS 计数";
lines(end+1) = "";
lines(end+1) = "| 邻域 | 严格 Lx/delta | 完整 SS | 截断 SS | 正/负完整 | 含完整 SS 的帧 | 触碰排除区 | 比例 |";
lines(end+1) = "|---:|---:|---:|---:|---:|---:|---:|---:|";
for i = 1:numel(summary.counts)
    item = summary.counts(i);
    lines(end+1) = sprintf('| %d | > %.1f | %d | %d | %d / %d | %d | %d | %.6g |', ...
        item.connectivity, item.length_threshold, item.complete_ss, ...
        item.censored_ss, item.positive_complete, item.negative_complete, ...
        item.frames_with_complete_ss, ...
        item.touching_user_exclusion_complete, ...
        item.touching_user_exclusion_fraction);
end
lines(end+1) = "";
lines(end+1) = "4/8 邻域完整 SS 长度分布摘要：";
lines(end+1) = "";
lines(end+1) = "| 邻域 | N | 中位 Lx/delta | P90 | P95 | 最大值 |";
lines(end+1) = "|---:|---:|---:|---:|---:|---:|";
for i = 1:numel(summary.connectivity_length_statistics)
    item = summary.connectivity_length_statistics(i);
    lines(end+1) = sprintf('| %d | %d | %.6g | %.6g | %.6g | %.6g |', ...
        item.connectivity, item.n, item.median, item.p90, item.p95, item.maximum);
end
lines(end+1) = "";
lines(end+1) = "8/4 邻域逐 frame-sign 对比（对象数单独统计，几何量为最长代表对象）：";
lines(end+1) = "";
lines(end+1) = "| Lx/delta | 8 帧符号检出 | 4 帧符号检出 | 8 对象 | 4 对象 | 同时 | 仅8 | 仅4 | Jaccard | 中位代表框 IoU |";
lines(end+1) = "|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|";
for i = 1:numel(summary.connectivity_frame_sign_comparison)
    item = summary.connectivity_frame_sign_comparison(i);
    lines(end+1) = sprintf('| > %.1f | %d | %d | %d | %d | %d | %d | %d | %.6g | %.6g |', ...
        item.LengthThreshold, item.Detected8, item.Detected4, ...
        item.ObjectCount8, item.ObjectCount4, item.Both, item.Only8, item.Only4, ...
        item.FrameSignJaccard, item.MedianBBoxIoU);
end
lines(end+1) = "";
lines(end+1) = sprintf(['主 8 邻域中可配对完整 SS：%d；matched-noSS：%d；' ...
    'unmatched：%d。'], summary.matching.eligible_complete_primary_ss, ...
    summary.matching.matched_pairs, summary.matching.unmatched_pairs);
lines(end+1) = "";
lines(end+1) = "## 条件谱";
lines(end+1) = "";
if isempty(spectra.energy_table)
    lines(end+1) = "没有合格 matched-noSS 对，因此没有条件谱；未放宽阈值。";
else
    lines(end+1) = "| Lx/delta | 测量行 | 配对数 | SS/noSS 大尺度能量比 |";
    lines(end+1) = "|---:|---|---:|---:|";
    for i = 1:height(spectra.energy_table)
        lines(end+1) = sprintf('| > %.1f | %s | %d | %.6g |', ...
            spectra.energy_table.LengthThreshold(i), ...
            spectra.energy_table.RowLabel(i), spectra.energy_table.PairCount(i), ...
            spectra.energy_table.SS_to_NoSS_LargeScaleRatio(i));
    end
end
lines(end+1) = "";
lines(end+1) = "这些谱只用于描述性验证；没有设置事后科学通过阈值，也不构成论文完整 v/w、uv/uw 自相似组成结论。";
lines(end+1) = "";
lines(end+1) = "## 代表帧与产物";
lines(end+1) = "";
lines(end+1) = sprintf('- 已选唯一完整 SS 对象：%d/30；不足时保留空槽，不伪造候选。', ...
    nnz(selection.Selected));
lines(end+1) = sprintf('- 全连通域目录：%d 行，按 48 帧批次分区为 MAT/CSV。', ...
    summary.frames.catalog_rows);
lines(end+1) = "- `mat/final_results.mat` 是紧凑权威结果；`catalog_mat/` 与 `catalog_csv/` 是完整逐对象目录。";
lines(end+1) = "";
lines(end+1) = "## 性能";
lines(end+1) = "";
lines(end+1) = sprintf('- 实测 %.6g s/帧（均值），按此估计 12000 帧识别为 %.3f h。', ...
    summary.performance.mean_seconds_per_frame, ...
    summary.performance.estimated_12000_frame_seconds / 3600);
text_value = strjoin(lines, newline);
text_value = text_value + newline;
end
